In [2]:
import numpy as np


---
# VIDEO: A zoo of matrices
---


In [3]:

# square vs. rectangular
S = np.random.randn(5,5)
R = np.random.randn(5,2) # 5 rows, 2 columns
print(R)

# identity
I = np.eye(3)
print(I)

# zeros
Z = np.zeros((4,4))
print(Z)

# diagonal
D = np.diag([ 1, 2, 3, 5, 2 ])
print(D)

# create triangular matrix from full matrices
S = np.random.randn(5,5)
U = np.triu(S)
L = np.tril(S)
print(L)

# concatenate matrices (sizes must match!)
A = np.random.randn(3,2)
B = np.random.randn(4,4)
C = np.concatenate((A,B),axis=1)
print(C)

[[-0.54453625 -1.21584153]
 [ 1.3142846   0.79800207]
 [-0.20304865 -0.41840905]
 [ 0.70902804  0.84878017]
 [-0.51094226  1.5671628 ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 2]]
[[-0.28018636  0.          0.          0.          0.        ]
 [ 1.64499743  1.1970577   0.          0.          0.        ]
 [ 0.02439617  0.24928658 -2.05660877  0.          0.        ]
 [ 1.5855717  -0.34793898  2.08107264  1.08504832  0.        ]
 [-0.41393014  0.14035697 -0.02642309  1.08518918 -1.53826391]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly


---
# VIDEO: Matrix addition and subtraction
---


In [3]:

# create random matrices
A = np.random.randn(5,4)
B = np.random.randn(5,3)
C = np.random.randn(5,4)

# try to add them
A+B
A+C



# "shifting" a matrix
l = .3 # lambda
N = 5  # size of square matrix
D = np.random.randn(N,N) # can only shift a square matrix

Ds = D + l*np.eye(N)
print(Ds)

ValueError: operands could not be broadcast together with shapes (5,4) (5,3) 


---
# VIDEO: Matrix-scalar multiplication
---


In [43]:
# define matrix and scalar
M = np.array([ [1, 2], [2, 5] ])
s = 2

# pre- and post-multiplication is the same:
print( M*s )
print( s*M )


[[ 2  4]
 [ 4 10]]
[[ 2  4]
 [ 4 10]]



---
# VIDEO: Diagonal and trace
---


In [10]:

M = np.round( 5*np.random.randn(4,4) )

# extract the diagonals
d = np.diag(M)

# notice the two ways of using the diag function
d = np.diag(M) # input is matrix, output is vector
D = np.diag(d) # input is vector, output is matrix
print(d)
print(D)

# trace as sum of diagonal elements
tr = np.trace(M)
tr2 = sum( np.diag(M) )
print(tr)
print(tr2)

[  4.  10.   4.   3.]
[[  4.   0.   0.   0.]
 [  0.  10.   0.   0.]
 [  0.   0.   4.   0.]
 [  0.   0.   0.   3.]]
21.0
21.0
