In [2]:
import numpy as np
import matplotlib.pyplot as plt
import math


---
# VIDEO: Computing rank: theory and practice
---


In [21]:
# make a matrix
m = 4
n = 6

# create a random matrix
A = np.random.randn(m,n)

# what is the largest possible rank?
ra = np.linalg.matrix_rank(A)
print('rank=' + str(ra))


# set last column to be repeat of penultimate column
B = A
B[:,n-1] = B[:,n-2]
rb = np.linalg.matrix_rank(B)
print('rank=' + str(rb))

rank=4
rank=4


In [29]:
## adding noise to a rank-deficient matrix

# square for convenience
A = np.round( 10*np.random.randn(m,m) )

# reduce the rank
A[:,m-1] = A[:,m-2]

# noise level
noiseamp = .001

# add the noise
B = A + noiseamp*np.random.randn(m,m)

print('rank (w/o noise) = ' + str(np.linalg.matrix_rank(A)))
print('rank (with noise) = ' + str(np.linalg.matrix_rank(B)))


rank (w/o noise) = 3
rank (with noise) = 4


In [46]:
#coding challenge
#create a rank-deficient matrix using matrix multiplication
#start with 10 x 10 matrix with rank 4
x = np.round(np.random.randn(10,4)*10)
y = np.round(np.random.randn(4,10)*10)
xy = np.matmul(x,y)
print(xy)
print(np.linalg.matrix_rank(xy))


[[ 323. -393.  206. -224.   22.  101.  294.  -14.  -38.  -22.]
 [-154.  125. -164.   20. -175.    5.  -12.  118.  -92.  184.]
 [  27.   -1.   48.   33.   96.  -53.  -59.  -67.   77. -125.]
 [ 235. -205.  160. -216.  -62.   25.  190.   62.  100.  -50.]
 [  52.  -70.   -6. -108. -126.   10.  108.   92.  -10.   72.]
 [ -50.    4.  -21.   85.   80.   82.  -17.  -67. -128.   63.]
 [  97. -365.   -8.  -44.   12.  325.  326.  -46. -504.  358.]
 [  94.   24.   45. -245. -280.    2.  137.  235.  168.   73.]
 [  82.  -97.   26. -163. -171.  149.  203.  133.  -93.  201.]
 [-209.   44. -156.  282.  189.   82. -120. -178. -322.  120.]]
4



---
# VIDEO: Rank of A^TA and AA^T
---


In [45]:

# matrix sizes
m = 14
n =  3

# create matrices
A = np.round( 10*np.random.randn(m,n) )

AtA = np.matrix.transpose(A)@A
AAt = A@np.matrix.transpose(A)

# get matrix sizes
sizeAtA = AtA.shape
sizeAAt = AAt.shape

# print info!
print('AtA: %dx%d, rank=%d' %(sizeAtA[0],sizeAtA[1],np.linalg.matrix_rank(AtA)))
print('AAt: %dx%d, rank=%d' %(sizeAAt[0],sizeAAt[1],np.linalg.matrix_rank(AAt)))


AtA: 3x3, rank=3
AAt: 14x14, rank=3


In [61]:
#coding challenge
#scalar multiplication and rank
l = 3
m = 6
n = 6
#full rank matrix
x = np.round(np.random.randn(m,n) * 10)
print(np.round(np.linalg.matrix_rank(x)))
print(np.linalg.matrix_rank(l * x))

#deficient rank matrix
y = np.round(np.random.randn(m,n) * 10)
y[:,m-2] = y[:,m-1]
print(np.linalg.matrix_rank(y))
print(np.linalg.matrix_rank(l * y))


6
6
5
5


In [72]:
#coding challenge
#rank of summed and multiplied matrices
a = np.round(np.random.randn(10,4) * 10)
b = np.round(np.random.randn(10, 4) * 10)
print(np.linalg.matrix_rank(a))
print(np.linalg.matrix_rank(b))
ata = np.matmul(a, a.T)
print(np.linalg.matrix_rank(ata))
btb = np.matmul(b, b.T)
print(np.linalg.matrix_rank(btb))
print(np.linalg.matrix_rank(np.matmul(ata, btb)))
print(np.linalg.matrix_rank(ata + btb))

4
4
4
4
4
8
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]



---
# VIDEO: Making a matrix full-rank by "shifting"
---


In [47]:
# size of matrix
m = 30

# create the square symmetric matrix
A = np.random.randn(m,m)
A = np.round( 10*np.matrix.transpose(A)@A )

# reduce the rank
A[:,0] = A[:,1]

# shift amount (l=lambda)
l = .01

# new matrix
B = A + l*np.eye(m,m)

# print information
print('rank(w/o shift) = %d' %np.linalg.matrix_rank(A))
print('rank(with shift) = %d' %np.linalg.matrix_rank(B))


rank(w/o shift) = 29
rank(with shift) = 30
